### ISSUE TITLE
MousePressed and MouseReleased

### ISSUE THREAD

**Issue by p10n** [globaltcad/swing-tree#1]
In addition to the mouseClicked events, it would be useful to have these two accessible as well. Especially MousePressed, when used for opeing popup menus. Menus usually open at the press rather than release (click). This feels more responsive, and in most cases allows to select an item from the menu in one go (by dragging and releasing, instead of releasing the mouse button and clicking a second time).

**Comment by Gleethos** [comment]
I am not sure I understand correctly.
Currently the following mouse event registration methods are available:
```java
  UI.panel("fill").withPrefSize(400, 400)
  .onMouseEnter( it -> System.out.println("Mouse entered panel") )
  .onMouseExit( it -> System.out.println("Mouse exited panel") )
  .onMousePress( it -> System.out.println("Mouse pressed panel") )
  .onMouseRelease( it -> System.out.println("Mouse released panel") )
  .onMouseClick( it -> System.out.println("Mouse clicked panel") )
  .onMouseDrag( it -> System.out.println("Mouse dragged panel") )
  ```
  Which includes the `onMousePress` and `onMouseRelease` methods.
  These two translate to the following raw Swing event listeners:
  ```java
    component.addMouseListener(new MouseAdapter() {
        @Override public void mousePressed(MouseEvent e) {
            //...
        }
    });
```
  and:
  ```java
    component.addMouseListener(new MouseAdapter() {
        @Override public void mouseReleased(MouseEvent e) {
            //...
        }
    });
```
Are these not what you mean or is the another kind of event that is missing here?

**Comment by Gleethos** [comment]
Any updates on this?

**Comment by p10n** [comment]
Ah, sorry - I obviously had overlooked them (lacking the help texts at that time, and/or wrong parentheses level which migh have hindered showing the autocomplete).
Regard this as my mistake.
